# Site
name: 'Qurious'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://tushar-ml.github.io'
disqus: 'qurious-1'
email: 'tushar.goel.ml@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
formspree_id: 'xrgvzyln'
include: ["_pages"]
comments: false
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    tushar:
      name:           Tushar
      linkedin:       https://www.linkedin.com/in/tushargoel-code
      avatar:         assets/images/avatar-tushar.png
      bio:            "Hi, I am Tushar, the author of Qurious and Senior ML Engineer, talks about ML and Quantum-Astro Physics"
      email:          tushar.goel.ml@gmail.com
      twitter:        https://twitter.com/tushargoel_ai
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: tushar
      avatar: assets/images/avatar-tushar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
