---
title: Tushar Ml.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: tushar
    avatar: assets/images/avatar-tushar.webp
- scope:
    path: _pages
  values:
    layout: page
name: Qurious
description: Mundana is a free Jekyll theme for awesome people like you, Medium like.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: ''
url: https://tushar-ml.github.io
disqus: qurious-1
email: tushar.goel.ml@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
formspree_id: xrgvzyln
include:
- _pages
comments: false
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-webp
authors:
  tushar:
    name: Tushar
    linkedin: https://www.linkedin.com/in/tushargoel-code
    avatar: assets/images/avatar-tushar.webp
    bio: Hi, I am Tushar, the author of Qurious and Senior ML Engineer, talks about
      ML and Quantum-Astro Physics
    email: tushar.goel.ml@gmail.com
    twitter: https://twitter.com/tushargoel_ai
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
webp:
  enabled: true
  quality: 75
  img_dir:
  - "/assets/images"
  nested: true
  formats:
  - ".jpeg"
  - ".jpg"
  - ".png"
  - ".tiff"
  gifs:
  - ".gif"
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false
